# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgts', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeDirectories',
            new_name='HomeDirectory',
        ),
        migrations.RemoveField(
            model_name='directoryshareing',
            name='owner',
        ),
        migrations.DeleteModel(
            name='DirectoryShareing',
        ),
        migrations.AddField(
            model_name='directorysharing',
            name='directory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.HomeDirectory'),
        ),
        migrations.AddField(
            model_name='directorysharing',
            name='sharedWith',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
