# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160902_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorysharing',
            name='directory',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='directorysharing',
            name='sharedWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homedirectory',
            name='homeDir',
            field=models.CharField(max_length=90, verbose_name="user's home directory"),
        ),
    ]
