# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160902_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharing',
            old_name='rgts',
            new_name='permissions',
        ),
        migrations.AlterField(
            model_name='sharing',
            name='item',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to=settings.AUTH_USER_MODEL),
        ),
    ]
