# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161012_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to=settings.AUTH_USER_MODEL),
        ),
    ]
